# Generated by Django 5.0.6 on 2026-04-30 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolio', '0001_initial'),
        ('submissions', '0001_initial'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioentry',
            name='submission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_entry', to='submissions.submission'),
        ),
        migrations.AddField(
            model_name='portfolioentry',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_entries', to='tasks.task'),
        ),
        migrations.AlterUniqueTogether(
            name='portfolioentry',
            unique_together={('student', 'task')},
        ),
    ]
