# Generated by Django 5.0.6 on 2026-04-30 18:37

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('github_pr_url', models.URLField(help_text='Ссылка на Pull Request или коммит', max_length=500)),
                ('demo_url', models.URLField(blank=True, help_text='Опционально: видео-демо или живой демо-URL', max_length=500)),
                ('description', models.TextField(help_text='Markdown: что сделано, как тестировать, заметки')),
                ('status', models.CharField(choices=[('in_review', 'In Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('revision_requested', 'Revision Requested')], db_index=True, default='in_review', max_length=25)),
                ('revision_number', models.PositiveSmallIntegerField(default=1, help_text='Номер итерации (растёт при каждом re-submit)')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('finalized_at', models.DateTimeField(blank=True, help_text='Когда компания approved/rejected', null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='tasks.task')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code_quality', models.PositiveSmallIntegerField(help_text='1–5: чистота кода, читаемость, conventions', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('architecture', models.PositiveSmallIntegerField(help_text='1–5: структура, разделение ответственности', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('correctness', models.PositiveSmallIntegerField(help_text='1–5: задача решена правильно, edge cases', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('documentation', models.PositiveSmallIntegerField(help_text='1–5: README, комментарии, описание PR', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('overall_score', models.DecimalField(decimal_places=2, help_text='Авто-рассчитанное среднее 1.00–5.00', max_digits=3)),
                ('feedback', models.TextField(help_text='Структурированный фидбек ментора')),
                ('requested_revision', models.BooleanField(default=False, help_text='Если True — ментор просит студента доработать')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='submissions.submission')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['status', '-submitted_at'], name='submissions_status_34029f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('submission', 'mentor')},
        ),
    ]
